version: '3.8'

services:
  cyberrange:
    build: .
    container_name: cyberrange
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.cyberrange.description=Ethical Hacking Training Platform"
      - "com.cyberrange.version=1.0"
    networks:
      - cyberrange-network

networks:
  cyberrange-network:
    driver: bridge

# Optional: Add volume for custom configurations
volumes:
  cyberrange-data:
    driver: local